---
title: "Praca domowa"
author: "Oferowane ceny mieszkań w grudniu 2016"

output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


W minionym tygodniu trafiłam na akrtykuł dotycznący średnich cen mieszkania w wybranych miastach Polski 
(http://www.bankier.pl/wiadomosc/Ceny-ofertowe-mieszkan-styczen-2017-Raport-Bankier-pl-7493142.html).

Zamieszczoną tabelę z danymi postanowiłam zwizualizować przy użyciu narzędzia Tableau . 
Na finalny Dashboard składają się trzy części - tabela z danymi, wykres średniej ceny na rynku wtórnym w funkcji średniej ceny na rynku pierwotnym oraz mapa Polski z zaznaczonymi miastami. 
Kolumny tabeli z danymi zostały uszeregowane względem malejącej ceny za mieszkanie o metrażu do 38mkw na rynku wtórnym. 
Wielkość punktów na mapie odpowiada średniej cenie za metr kwadratowy mieszkania w danym mieście na rynku pierwotnym. 
Kolory na wykresie oraz mapie pokrywają się ze sobą, a umieszczone dwa filtry dla miasta i metrażu pozwalają na szybkie wybieranie lub podświetlanie interesujących nas wielkości.

https://public.tableau.com/profile/publish/PdTWD/Dashboard1#!/publish-confirm

Wykresy potwierdzają przypuszczenia, że ,,królową'' rankingu jest Warszawa- to tu zapłacimy najwięcej za metr kwadratowy mieszkania niezależnie od jego metrażu i rodzaju ( rynek pierwotny i wtórny).
Prawie wie wszystkich miastach najwięcej zapłacimy za metr kwadratowy mieszkania o najmniejszym metrażu ( jedynie Łódź nie posiada tej właściwości). Natomiast Gdańsk charakteryzuje się największą różnicą między ceną dla najmniejszego matrażu, a pozostałymi dwoma.
