new function(e,Q,s,g,r,h,R,M,ja,$){typeof _gao_inscdwl_cfg===h&&(Q._gao_inscdwl_cfg=function(d){typeof _gde_insdwl_cfg===h&&(Q._gde_insdwl_cfg=[]);typeof d.c!=h&&typeof d.b!=h&&_gde_insdwl_cfg.push({id:d.id,c:d.c,b:d.b,o:d.o||1E3,h:d.h||3E4,w:d.w||72E5,i:d.i,l:d.l,k:d.k,s:d.s||1E3,u:d.u||18E5,t:d.t||72E5})});typeof _gao_insdwl===h?_gao_insdwl=new function(d){function B(){return(new Date).getTime()}function Q(a){function b(){}if(!U(a))return function(a){a(!1)};if(!a.frames){a.frames=[];var c=e.createElement("iframe");
c.Q="0";c.R="0";c.P="0";var q,f=a.c.split("/");q=f[0]+"//"+f[2];aa&&(c.src=q+"/gdejs/poly.html");var f={position:"absolute",border:"none",opacity:"0.0001",filter:"alpha(opacity=0)",pointerEvents:"none",width:"1px",height:"1px",visibility:"hidden",display:"none"},l;for(l in f)c.style[l]=f[l];var k=Math.random();n("load",function(){c.contentWindow.postMessage("frameKey:"+k,q);c.contentWindow.postMessage("frameFg:"+a.i,q)},c);n("message",function(a){a.data&&(a=a.data.split(":"),"mozFrameVisible"==a[0]&&
a[1]==k?c.mozFrameVisible="true"==a[2]:"IE8"==a[0]&&a[1]==k&&(c.style.width="5px",c.style.height="5px"))},d);(l=e.getElementsByTagName("body")[0])&&a.frames.push(l.appendChild(c))}c=a.frames[0];d[M]&&(c.L=c.contentWindow[M]);c.style.top=a.offset().top+(a.e()>>1)+"px";c.style.left=a.offset().left+(a.f()>>1)+"px";c.style.visibility="visible";c.style.display="block";typeof d[M]!=h?setTimeout(function(){c.contentWindow[M]>c.L?b(!0):b(!1);c.style.visibility="hidden";c.style.display="none"},150):setTimeout(function(){b(c.mozFrameVisible)});
return function(a){b=a}}function ka(a){a.n||(a.p?S(a):a.A||(a.A=D(x(function(a){a.p=g;S(a)},a,a),a.o)))}function ba(a){!a.p&&a.A?(clearTimeout(a.A),a.A=r):a.p&&a.n?S(a):y(a.a,e)?a.j(N()?2:3):V(a)}function la(){e[E]?W():F()}var ca,ma,U,X,n,y,G,na,oa=d.encodeURIComponent,aa,pa,qa,W,ra=[],Y,sa=[],Z,F,S,V,da,H,u,I,N,z,ta,ua,va,wa,J,ea,xa,ya,fa,za,x,ga,D,p,K,ha,Aa,ia,O,v={},Ba=0,L=[],T,Fa=0<Object.prototype.toString.call(d.HTMLElement).indexOf("Constructor"),Ga=!!d.opera||0<=d.navigator.userAgent.indexOf(" OPR/"),
Ha=/(iPad|iPhone|iPod|Mac )/g.test(d.navigator.userAgent);new function(a,b,c){T=d[a]&&d[a][b]&&d[a][b][c]?d[a][b][c]:B()}("performance","timing","navigationStart");v.q=v.init=v.F=function(){var a=d._gde_insdwl_id,b=d._gde_inscreen,c=d._gde_inscreen_end,q=d._gde_insdwl_tm,f=d._gde_inscreen_fg,l=d._gde_dwell||{},k=d._gde_dwell_end||{},t=d._gde_insdwl_dwltm;typeof _gde_insdwl_id!==h&&p(_gde_insdwl_id,function(d,m){_gao_inscdwl_cfg({id:a[m],c:b[m],b:c[m],o:q&&(q[m]||[])[0],h:q&&(q[m]||[])[1],w:q&&(q[m]||
[])[2],i:f&&f[m],l:l[m],k:k[m],s:t&&(t[m]||[])[0],u:t&&(t[m]||[])[1],t:t&&(t[m]||[])[2]});delete _gde_insdwl_id[m]});typeof _gde_inscreen_dwell!==h&&p(_gde_inscreen_dwell,function(a,b){_gao_inscdwl_cfg({id:function(){var a=e.getElementById(b),c=a;if(a)return a=a.parentNode,a.removeChild(c),a},c:a,b:a,i:f&&f[b],l:a,k:a});delete _gde_inscreen_dwell[b]});typeof _gde_insdwl_cfg!==h&&(Ba++,_gde_insdwl_cfg=K(_gde_insdwl_cfg,function(a){var b="function"===typeof a.id?a.id():"string"===typeof a.id?e.getElementById(a.id):
a.id;if(!b)return g;if(K(L,function(a){if(a.a===b||y(b,a.a)||y(a.a,b))return g})[0]!=r)return s;var c={a:b,parentNode:function(a){for(;a&&a.parentNode;)a=a.parentNode;return a}(b),v:[],j:function(a,b,c){var m=this.v[this.v.length-1];m&&m.state===a||this.v.push({K:c||B(),state:a,visible:b,N:N()})},n:0,d:0,c:a.c||"",b:a.b||"",i:a.i,r:ya(a),C:[],J:0,o:a.o,h:a.h,w:a.w,m:s,g:s,l:a.l||"",k:a.k||"",s:a.s,u:a.u,t:a.t,offset:function(){return this.G()[2]},f:function(){return this.G()[0]},e:function(){return this.G()[1]},
G:function(){var a=[],b=20;return function(){20<=b++&&(a[0]=this.a.offsetWidth,a[1]=this.a.offsetHeight,a[2]=ca(this.a),b=0);return a}}()};checkIsIframe()&&!U(c)?c.j(1,s,T):c.j(N()?2:3,s,T);n("mouseup",function(a){if(200>=++c.J){var b=ca(c.a);c.C.push([a.pageX-b.left,a.pageY-b.top])}c.m||(u(c.c+z(c,{isn:"4",isn_d:B()-T})),c.m=g,c.p=g)},b,!0);L.push(c);if(b.parentNode){do(b.scrollWidth>b.offsetWidth||b.scrollHeight>b.offsetHeight)&&n("scroll",F,b);while(b=b.parentNode)}c.l&&c.k&&qa(c)}),0<_gde_insdwl_cfg.length&&
30>Ba&&D(x(v.F,v),200),Z())};checkIsIframe=function(){return d.self!==d.top};U=function(a){return!(typeof d[M]==h&&(!aa||typeof d.chrome==h&&!a.i))};aa=function(){if(typeof d[M]!=h||Ha)return!1;var a=!1;try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash")&&(a=!0)}catch(b){d.navigator.mimeTypes&&d.navigator.mimeTypes["application/x-shockwave-flash"]&&d.navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=!0)}return a}();pa=function(){d[ja]=!1;var a,b="FFFFFF",c;n("message",function(m){if(m.data){var d=
m.data.split(":");"frameKey"==d[0]?(c=m.origin,a=d[1],"undefined"!=typeof IE8&&parent.postMessage("IE8:"+a,c)):"frameFg"==d[0]&&(b=d[1])&&b.charAt&&"#"==b.charAt(0)&&(b=b.substr(1))}},d);var q,f=d.setMozFrameVisible=function(b){parent.postMessage("mozFrameVisible:"+a+":"+b,c)};d.getFg=function(){return b};var l,k,t={allowScriptAccess:"always",quality:"high",scale:"noscale",salign:"lt"},g={position:"absolute",left:"0px",top:"0px",right:"0px",bottom:"0px",width:"1px",height:"1px"},m={padding:"0",margin:"0",
width:"100%",height:"100%",pointerEvents:"none",overflow:"hidden"};t.wmode=d.isIE||typeof d.chrome==h||Ga?"direct":"transparent";if(Fa){t.wmode="transparent";var Ia=ga(function(){var a=l.parentNode;l.parentNode.removeChild(l);a.appendChild(l)},250),w;d.setMozFrameVisible=function(a){a?(q&&(q=clearTimeout(q)),w&&(w=clearTimeout(w)),f(!0),w=setTimeout(function(){Ia();q=setTimeout(function(){f(!1);q=null},500);w=null},500)):f(!1)}}if(d.isIE){t.movie=$;var C="";k=function(a,b){C+='<param name="'+b+'" value="'+
a+'" />'};C+='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" data="'+$+'" type="application/x-shockwave-flash">';p(t,k);C+="</object>";e.write(C);l=e.getElementsByTagName("object")[0]}else t.movie=$,k=function(a,b){var c=e.createElement("param");c.setAttribute("name",b);c.setAttribute("value",a);l.appendChild(c)},l=e.createElement("object"),p(t,k);for(var Ca in g)l.style[Ca]=g[Ca];n("load",function(){var a=e.getElementsByTagName("body")[0];if(a){for(var b in m)a.style[b]=m[b];isIE||
a.appendChild(l)}})};S=function(a){0!=a.n?(a.d+=B()-a.n,a.d=ea(a),a.n=0,a.d>=a.h&&!J(a)&&H(a)&&u(a.b+z(a,{isn:"1",isn_t:a.h})),a.B&&(clearTimeout(a.B),a.B=r),J(a)||(y(a.a,e)?a.D=D(x(V,a,a),a.w):V(a)),a.j(N()?2:3)):(da(a)&&(ua(a),u(a.c+z(a,{isn:"0",isn_d:B()-T}))),a.n=B(),a.d=ea(a),J(a)||(a.B=D(x(function(a){a.B=r;a.d=a.h;H(a)&&u(a.b+z(a,{isn:"1",isn_t:a.d}))},a,a),a.h-a.d)),clusterClearTimeout(a),a.j(4,g))};da=function(a){return a.m?s:a.m=g};H=function(a){if(a.g)return s;a.g=g;return wa(a)};V=function(a){if(a.g||
J(a))return s;a.D=r;H(a)&&u(a.b+z(a,{isn:"3",isn_t:a.d}));return g};clusterCreatives=function(a){return a.r?K(L,function(b){return b.r==a.r&&b!==a}):s};ua=function(a){ia(clusterCreatives(a),function(a){da(a)})};va=function(a){return O(clusterCreatives(a),function(a,c){return a||c.m},a.m)};clusterClearTimeout=function(a){p(clusterCreatives(a).concat([a]),function(a){a.D&&(clearTimeout(a.D),a.D=r)})};wa=function(a){if(J(a))return s;p(clusterCreatives(a),H);return g};J=function(a){return O(clusterCreatives(a),
function(a,c){return a||c.g},s)};ea=function(a){return O(clusterCreatives(a),function(a,c){return Math.max(c.d,a)},a.d)};xa=function(a){return O(clusterCreatives(a),function(a,c){return(c.I||0)+a},a.I||0)};ya=function(a){return a.c.split("redot")[1]||a.c};var Da=[];fa=function(a,b){Da.forEach(function(c){c.H.r==a.r&&c.H!==a&&c.M(b)})};za=function(a,b){Da.push({H:a,M:b})};ta=function(a){var b={nisn_t:0,nisninac_t:0,nisnout_t:0,nisnunrec_t:0};a.j(5);O(a.v,function(a,c){if(!c.visible){var d=c.K-a.K;
b.nisn_t+=d;1===a.state&&(b.nisnunrec_t+=d);if(2===a.state||3===a.state)a.N?b.nisnout_t+=d:b.nisninac_t+=d}return c},a.v.splice(0,1)[0]);for(var c in b)0==b[c]&&delete b[c];u(a.b+z(a,b))};W=function(){I&&(clearInterval(I),I=r);p(L,function(a){ba(a)});p(ra,function(a){a(W)})};Y=function(){u[R].O=!0;p(A.splice(0,A.length),u);p(L,function(a){a.p?(S(a),a.c&&""!=a.c&&!a.g&&H(a)&&u(a.b+z(a,{isn:"2",isn_t:a.d}))):va(a)||J(a)||(H(a),ta(a))});p(sa,function(a){a(Y)})};u=function(a){0<a.indexOf("[TIMESTAMP]")&&
(a=a.split("[TIMESTAMP]").join((new Date).getTime()));if(!u[R].O||typeof XDomainRequest==h&&typeof XMLHttpRequest==h)A.push(a);else{var b=new (typeof XDomainRequest!=h?XDomainRequest:XMLHttpRequest);try{d.chrome&&(b.withCredentials=g),b.open("GET",a,!1),b.send(null)}catch(c){}}};var A=[];A.push=function(a){return function(){a.apply(A,arguments);D(A.flush,50)}}(A.push);A.flush=function(){p(A.splice(0,A.length),function(a){(new Image(1,1)).src=a})};y=function(a,b){if(a==r||a===b)return a===b;do if(a===
b)return g;while(a=a.parentNode);return s};na=function(a){var b=a.f()/2,c=a.e()/2;if(!G)return g;var d=a.a.getBoundingClientRect(),f=K([[5,d.left+1,d.top+1],[6,d.left+a.f()-1,d.top+1],[10,d.left+a.f()-1,d.top+a.e()-1],[9,d.left+1,d.top+a.e()-1]],function(b){return y(G(b[1],b[2]),a.a)});if(3<=f.length)return g;if(2==f.length){if(0<(f[0][0]&4)&&0<(f[1][0]&4))return y(G(f[0][1],f[1][2]+c),a.a);if(0<(f[0][0]&8)&&0<(f[1][0]&8))return y(G(f[0][1],f[1][2]-c),a.a);if(0<(f[0][0]&1)&&0<(f[1][0]&1))return y(G(f[0][1]+
b,f[1][2]),a.a);if(0<(f[0][0]&2)&&0<(f[1][0]&2))return y(G(f[0][1]-b,f[1][2]),a.a)}if(1==f.length){var b=a.a,e;do if(b.scrollWidth>b.offsetWidth||b.scrollHeight>b.offsetHeight){e=b.getBoundingClientRect();break}while(b=b.parentNode);if(e){var b=a.f()*a.e(),k;5==f[0][0]?k=[e.bottom-d.top,e.right-d.left]:6==f[0][0]?k=[e.bottom-d.top,d.right-e.left]:10==f[0][0]?k=[d.bottom-e.top,d.right-e.left]:9==f[0][0]&&(k=[d.bottom-e.top,e.right-d.left]);return.5<k[0]*k[1]/b}}return s};Z=checkIsIframe()?function(){return function(){I||
(I=setInterval(x(F,v),500));p(L,function(a){a.g||(U(a)?!a.g&&0<a.f()&&0<a.e()&&Q(a)(function(b){b?ka(a):ba(a)}):a.j(1))})}}():function(){I||(I=setInterval(x(F,v),500));var a=ma(),b=X();p(L,function(c){c.g||(N()&&0<c.f()&&0<c.e()&&!(c.offset().left+b.left<-c.f()/2||c.offset().left+b.left>a.width-c.f()/2||c.offset().top+b.top<-c.e()/2||c.offset().top+b.top>a.height-c.e()/2)&&na(c,c.offset())?ka(c):ba(c))})};qa=function(a){var b,c,d,f,l,k,h,g;f=function(a){return c(function(b,c){if(0==b)return l(a+c);
if(7==b)return h(a)})};l=function(b){return d(function(c,d){if(5==c)return u(a.b+z(a,{dlw:"0",dlw_d:b+d})),k(0);if(1==c||3==c)return f(b+d)},a.s)};k=function(b){fa(a,7);return d(function(a,c){if(1==a||3==a)return h(b+c);if(5==a)return g(b+c,6);if(4==a)return g(b+c,4)},a.u-b)};h=function(b){return d(function(a){if(0==a)return k(b);if(5==a||4==a||9==a)return g(b,a)},a.t)};g=function(b,d){a.I=b;if(9!=d){fa(a,9);var e={6:1,4:2,5:3};0<e[d]&&u(a.b+z(a,{dlw:e[d],dlw_t:xa(a)}))}return c(function(){})};b=
function(){var a,e=B(),w;c=function(a){w&&(clearTimeout(w),w=r);return a};d=function(c,d){w&&clearTimeout(w);w=D(function(){a===c&&(b(5),w=r)},d);return c};a=f(0);return function(b){(b=a(b,B()-e))&&b!==a&&(a=b,e=B())}}();ra.push(function(){b(3)});sa.push(function(){b(4)});n(["mousemove","mouseenter","mouseover"],function(){b(0)},a.a);n(["mouseleave","mouseout"],function(){b(1)},a.a);n("mousewheel",function(c){var d=X(),f=c.clientX-d[0],C=c.clientY-d[1];D(function(){d=X();var c=e.elementFromPoint(f+
d[0],C+d[1]);y(c,a.a)?b(0):b(1)},0)},e);za(a,b)};(function(){var a=Array[R],b=a.slice,c=Object[R].hasOwnProperty,d=a.forEach,e=a.map,l=a.reduce,k=a.filter,a=Object.keys,g=Function[R].bind,a=Object.keys,h={};x=function(a,c){if(a.bind===g&&g)return g.apply(a,b.call(arguments,1));var d=b.call(arguments,2);return function(){return a.apply(c,d.concat(b.call(arguments)))}};D=function(a,c){var d=b.call(arguments,2);return setTimeout(function(){return a.apply(r,d)},c)};ga=function(a,b){function c(){g=new Date;
f=r;k=a.apply(d,e)}var d,e,f,k,g=0;return function(){var h=new Date,l=b-(h-g);d=this;e=arguments;0>=l?(clearTimeout(f),f=r,g=h,k=a.apply(d,e)):f||(f=setTimeout(c,l));return k}};ha=function(a,b){return c.call(a,b)};p=function(a,b,c){if(a!=r)if(d&&a.forEach===d)a.forEach(b,c);else if(a.length===+a.length)for(var e=0,f=a.length;e<f&&b.call(c,a[e],e,a)!==h;e++);else for(e in a)if(ha(a,e)&&b.call(c,a[e],e,a)===h)break};K=function(a,b,c){var d=[];if(a==r)return d;if(k&&a.filter===k)return a.filter(b,c);
p(a,function(a,e,f){b.call(c,a,e,f)&&(d[d.length]=a)});return d};Aa=a||function(a){if(a!==Object(a))throw new TypeError("Invalid object");var b=[],c;for(c in a)ha(a,c)&&b.push(c);return b};ia=function(a,b,c){var d=[];if(null==a)return d;if(e&&a.map===e)return a.map(b,c);p(a,function(a,e,f){d.push(b.call(c,a,e,f))});return d};O=function(a,b,c,d){var e=2<arguments.length;null==a&&(a=[]);if(l&&a.reduce===l)return d&&(b=x(b,d)),e?a.reduce(b,c):a.reduce(b);p(a,function(a,f,k){e?c=b.call(d,c,a,f,k):(c=
a,e=!0)});if(!e)throw new TypeError(reduceError);return c}})();ca=function(a){var b={top:0,left:0};typeof a.getBoundingClientRect!==h&&(b=a.getBoundingClientRect());a=e.documentElement;return{top:b.top+(d.pageYOffset||a.scrollTop)-a.clientTop,left:b.left+(d.pageXOffset||a.scrollLeft)-a.clientLeft}};ma=function(){return"CSS1Compat"!=e.compatMode?{width:e.body.clientWidth,height:e.body.clientHeight}:{width:e.documentElement.clientWidth,height:e.documentElement.clientHeight}};X=function(){return[void 0!==
d.pageXOffset?d.pageXOffset:(e.documentElement||e.body.parentNode||e.body).scrollLeft,void 0!==d.pageYOffset?d.pageYOffset:(e.documentElement||e.body.parentNode||e.body).scrollTop]};e.elementFromPoint&&(G=x(e.elementFromPoint,e));n=function(){return function(a,b,c,e){if({array:g,object:g}[typeof a])return K(a,function(a){n(a,b,c)});c||(c=d);c.addEventListener?c.addEventListener(a,x(b,v),e||!1):c.attachEvent&&c.attachEvent("on"+a,x(b,v));return b}}();F=ga(Z,150);n("scroll",F);n("resize",F);n("beforeunload",
Y);n("unload",Y);n("load",v.F);d.self===d.top&&n("blur",W);n("focus",Z);var E,P=s;typeof e.hidden!==h?(E="hidden",P="visibilitychange"):typeof e.mozHidden!==h?(E="mozHidden",P="mozvisibilitychange"):typeof e.msHidden!==h?(E="msHidden",P="msvisibilitychange"):typeof e.webkitHidden!==h&&(E="webkitHidden",P="webkitvisibilitychange");P&&(n(P,la,e),la());N=E!=r?function(){return!e[E]}:function(){return g};z=function(a,b){b=b||{};var c=oa(ia(Aa(b),function(a){return a+"="+b[a]}).join("|"));if(0<a.C.length){var d=
c.length+10,e=[],g=[];a.C=K(a.C,function(a){d+=6+a.join("").length;if(1024>=d)e.push(Math.min(Math.max(0,a[0]),65535)>>0),g.push(Math.min(Math.max(0,a[1]),65535)>>0);else return!0});0<e.length&&g.length==e.length&&(c+=oa("|hx="+e.join(",")+"|hy="+g.join(",")+(200<=a.J?"|hn=1":"")+(1024<d?"|hl=1":"")))}return"&extra="+c};var Ea=(new Date).getTime(),Ja=setInterval(function(){if("complete"==e.readyState||"interactive"==e.readyState||1E4<(new Date).getTime()-Ea)("complete"==e.readyState||1E4<(new Date).getTime()-
Ea)&&clearInterval(Ja),v.F()},250);"complete"!=e.readyState&&"interactive"!=e.readyState||v.F();d[ja]&&pa();return v}(Q):"complete"!=e.readyState&&"interactive"!=e.readyState||_gao_insdwl.q()}(document,window,!1,!0,null,"undefined","prototype","mozPaintCount","_gde_inscreen_poly","poly.swf");
