---
output: html_document
---
 
```{r, echo=FALSE, message=FALSE}
library(knitr)
library(dplyr)
library(eurostat)
library(ggiraph)
```  
   



```{r, echo=FALSE, message=FALSE}
migranci<-search_eurostat("migr", type = "dataset")

dat <- get_eurostat(id = "lfso_14leecm", time_format = "num") 

dat <- label_eurostat(dat)

dane<- dat %>% filter( geo=="Poland", values!='NA' , type_con == 'Total', mgstatus=="Total" )
dane<-dane[,-c(1,3,5,6,7)]
dane<-dane[-which((dane$swmethod %in% c("Total","No response")) | (dane$isced11 =="All ISCED 2011 levels") ),]

dane<-dane[-c(1:3),]

dane[16,3]<-dane[7,3]+dane[13,3]
dane[17,3]<-dane[8,3]+dane[14,3]

dane<-dane[-c(13,14),]

colnames(dane)<-c("metoda","edukacja","values")

dane$metoda<-as.character(dane$metoda)
dane$metoda<- as.factor(dane$metoda)

levels(dane$metoda)<-c("Biuro zatrudnienia",
                       "Pracodawca kontaktuje sie osobiscie","Nie dotyczy","Inna metoda",
                       "Kontakt osobiscie z pracodawca","Rodzina/znajomi","Ogloszenie")

dane$edukacja<-as.character(dane$edukacja)
dane$edukacja<- as.factor(dane$edukacja)

levels(dane$edukacja)<-c("Podstawowe/gimnazjalne", "Srednie","Wyzsze")

tooltip<-c()

for(i in 1:21){
  tooltip[i]<- paste0("Metoda znalezienia pracy: \n", dane$metoda[i],"\n Wyksztalcenie: ", dane$edukacja[i], "\n Procent: ",dane$values[i])
}

levels(dane$metoda)<-c("Biuro zatrudnienia",
                       "Pracodawca kontaktuje \nsie osobiscie","Nie dotyczy","Inna metoda",
                       "Kontakt osobiscie \nz pracodawca","Rodzina/znajomi","Ogloszenie")

dane$metoda = factor(dane$metoda,levels(dane$metoda)[c(2,4,1,7,5,6,3)])

dane$values[which(dane$values>=25)]<-25
levels(dane$edukacja)<-c("Podstawowe", "Srednie","Wyzsze")

p<-ggplot(data=dane, aes(x=edukacja,y=values, fill=metoda, tooltip=tooltip))+
  geom_bar_interactive(stat="identity",position = "dodge")+
  scale_fill_manual(values=c("#fed976","#feb24c","#fd8d3c","#fc4e2a","#e31a1c","#bd0026","#800026"),
        name="Metoda znalezienia pracy:")+
  theme_bw() + 
  theme(axis.text.x = element_text(hjust = 0.5, size=11, face="bold"),
        axis.text.y = element_text(hjust = 0.9, vjust=0.5, size=11, face="bold"),
        axis.title.x = element_text(hjust = 0.5, size=12, face="bold"),
        axis.title.y = element_text(hjust = 0.5, size=12, face="bold"),
        plot.title=element_text( hjust=0, size=18, face="bold"))+
  xlab("Wyksztalcenie")+
  ylab("Procent migrantow" )+
  ggtitle("Metody znalezienia pracy przez migrantow \nw Polsce z podzialem na wyksztalcenie ")+
  scale_y_continuous(expand = c(0, 0.03),limits=c(0,25),
                     labels=c(seq(0,20,by=5), ">25"))

ggiraph(code = print(p))

```
Polskie znaki na wykresie zostaly dodane podczas obróki pliku html. 




 